language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: jIL4VVXOulNGaLB7DG7VqXXNmDsSHH7sdOZ5IcXz3zldUz7XuGxjSXyixH7p7Rv43wo9+dqQHyl0C/T1kfMoJ0llOw4aPKC2LLByKJ8tgT/ZKQkMS+qQMXmO0XXWgaPB04CPqTT4ociBDPgR6R2yt1qeLSYrich0CoWhN0VlTNFbgrN3TyMgMW3EoOFIRWTAbI83cEDzqObVTLln1N9kXHZHsLk+9tCgjISf83z9oaWntrZK8zhRdHLRhLGa4zBs6ZZvR54w6JQPwokI23uIulYz//TF4cFv27UMx5uf3Y9RQasUxh5I0HnujGFZ5xIWluuxLeOkt6O9WYMyVLssqW5fmLJOqwBdC6FGmw6y7albitRLamYTFpcxZM54wx1/y9W6H9IVLOZVJ/D9amplS1U/X0JpgxgRNUZiy/DFyt1CHVTqfwEknx2aq4n7VtX/OENyi3Qg0Q/j44oIu63amXIInRroyT966bi0hlANIWl5ykMMx2znXL/NWXcqWDH7S/7UGZGUlH5b4RdKBt9Gxbr0Dyql86KkKeVzgqg1z0Hv1wpp+xTam3VSxYZYGNXuAWMjilq2qYIx6o8sjvU7cbNy74TW7B4XLAMeUDFs3xLsNsgdyXQMiCQpikL8iJ7RdsdOGR9k/D4OIHRXG1aIGQO/KM5kDyXovP5xEXFVG1M=
  app: Parkometer
  on:
    repo: vittin/Parkometer
