language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: "b5DFJFalRQXa7LAbGZ6D+z2b7gvgoGOLmL/xr8MDXnzA7ssIBfOBXEpkD525kh09aafmr8GmExR0SKCy31oIf1tCXCFMIznaqYw2SVrdNbtQfBGyvWzqOb0uy4RCnWMOLCL5zFPKDsDrx57ezTy365KK+JBgACWNivS93Vtvb4XYPOCOfUAFfzXclRxlS0CHZWafh7S3J64cz/LB8Z6dYBPcDfnzLSzYNE1MU8eYF7QUFBRXwH8r5bWOcd7ZNe0kimR6bSLAH0OJ5RI1+LL1In8gvjhAZMXFkGNbDFNvchTKOTrbOqxQtuS0inSwEwVRAmZhILoTn/KmAGSYkH3WVPQOQ0+RvPU21kg58MMBzI6RPbSwqAzf/MXMRZLna9dflVL0tWV0SspLBO0rAavT9SbRukXQIgaRa4MU9TJNIpD/PnIXfOsVUOi2Mcmkzdtzy2sQXKf23zfA8HMbnBmySgaiKurryr8ITmTkYfdxU1nmJuRu1ZdvD+58IIi7t8+H8jl0TXnPn0VslhADo803wO7E87Op2HO7bm8piLbYS2awxvUeJLDcNWhFU8Ulr1jFmEZqD/WebU5HXkEJ2xKzVi5A3J9DE29W1WNL6RvDh7j9S/3GByHldJs4BTb7L8V8YnIzTpuvH4B/l1fGCpruuPkaG7Kymz/QohovXo0zFMo="
